name: Build SukiSU Ultra V2
on:
  workflow_dispatch:
    inputs:
      FEIL:
        description: Device
        required: true
        type: choice
        options:
          - oneplus_ace5
          - oneplus_ace5_b
          - oneplus_ace5_pro_b
          - oneplus_13_b
          - oneplus_12_b
          - oneplus_11_b
          - oneplus_10t_v
          - oneplus_ace3_b
          - oneplus_ace2_b
        default: oneplus_ace5
      CPU:
        description: CPU
        required: true
        type: choice
        options:
          - sm8650
          - sm8750
          - sm8550
          - sm8475
          - sm8450
          - mt6991
        default: sm8650
      ANDROID_VERSION:
        description: Android Version
        required: true
        type: choice
        options:
          - android14
          - android15
          - android13
          - android12
        default: android14
      KERNEL_VERSION:
        description: Kernel Version
        required: true
        type: choice
        options:
          - "6.1"
          - "6.6"
          - "5.15"
          - "5.10"
        default: "6.1"
      SUSFS:
        description: SUSFS
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "On"
      KPM:
        description: KPM
        required: true
        type: choice
        options:
          - "Off"
          - "On"
        default: "Off"
      lz4kd:
        description: lz4kd
        required: true
        type: choice
        options:
          - "Off"
          - "On"
        default: "Off"
      bbg:
        description: Baseband-Guard
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "On"
      bbr:
        description: BBR
        required: true
        type: choice
        options:
          - "Off"
          - "On"
        default: "Off"
      proxy:
        description: Proxy Optimization
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "On"
permissions:
  contents: write
env:
  CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
  CCACHE_NOHASHDIR: "true"
  CCACHE_HARDLINK: "true"
  CCACHE_MAXSIZE: 8G
jobs:
  build:
    name: "Build ${{ github.event.inputs.FEIL }} K=${{ github.event.inputs.KERNEL_VERSION }} SUSFS=${{ github.event.inputs.SUSFS }}"
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        if: ${{ github.event.inputs.KERNEL_VERSION == '5.10' || github.event.inputs.KERNEL_VERSION == '5.15' }}
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Checkout Builder
        uses: actions/checkout@v4
      - name: Setup ccache
        run: |
          echo "CCACHE_DIR=$HOME/.ccache_${{ github.event.inputs.FEIL }}_SukiSU" >> $GITHUB_ENV
          mkdir -p "$HOME/.ccache_${{ github.event.inputs.FEIL }}_SukiSU"
      - name: Configure Git
        run: |
          git config --global user.name "build"
          git config --global user.email "2210077278@qq.com"
      - name: Cache and Install Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: python3 git curl ccache libelf-dev build-essential flex bison libssl-dev libncurses-dev liblz4-tool zlib1g-dev libxml2-utils rsync unzip gawk dos2unix python3-pip
          execute_install_scripts: true
      - name: Restore ccache
        uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ github.event.inputs.FEIL }}-SukiSU-SUSFS-${{ github.event.inputs.SUSFS }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ github.event.inputs.FEIL }}-SukiSU-SUSFS
            ccache-${{ runner.os }}-SukiSU-SUSFS
      - name: Initialize ccache
        run: |
          ccache -M ${{ env.CCACHE_MAXSIZE }}
          ccache -s
      - name: Install Repo Tool
        run: |
          curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo
      - name: Clone Kernel Source
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/Xiaomichael/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
          sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/external/dtc/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '''s/-dirty//g''')' kernel_platform/common/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '''s/-dirty//g''')' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '''s/-dirty//g''')' kernel_platform/external/dtc/scripts/setlocalversion
          if [ "${{ github.event.inputs.KERNEL_VERSION }}" != "6.6" ]; then
            sed -i '$s|echo "\$res"|echo "-${{ github.event.inputs.ANDROID_VERSION }}-oki-xiaoxiaow"|' kernel_platform/common/scripts/setlocalversion
            sed -i '$s|echo "\$res"|echo "-${{ github.event.inputs.ANDROID_VERSION }}-oki-xiaoxiaow"|' kernel_platform/msm-kernel/scripts/setlocalversion
            sed -i '$s|echo "\$res"|echo "-${{ github.event.inputs.ANDROID_VERSION }}-oki-xiaoxiaow"|' kernel_platform/external/dtc/scripts/setlocalversion
          else
            ESCAPED_SUFFIX=$(printf '%s\n' "-${{ github.event.inputs.ANDROID_VERSION }}-oki-xiaoxiaow" | sed 's:[/\&]:\\&:g')
            sudo sed -i "s/-4k/$ESCAPED_SUFFIX/g" kernel_platform/common/arch/arm64/configs/gki_defconfig
            sed -i 's/${scm_version}//' kernel_platform/common/scripts/setlocalversion
            sed -i 's/${scm_version}//' kernel_platform/msm-kernel/scripts/setlocalversion
          fi
      - name: Setup Baseband-guard
        if: ${{ github.event.inputs.bbg == 'On' && github.event.inputs.KPM == 'Off' }}
        run: |
          set -e
          cd kernel_workspace/kernel_platform/common
          curl -sSL https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh -o setup.sh
          bash setup.sh
      - name: Setup SukiSU Ultra
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/builtin/kernel/setup.sh" | bash -s builtin
          cd KernelSU
          curl -L -o sukisu_setup.bin https://github.com/Xiaomichael/OnePlus-Actions/raw/Build/script/sukisu_setup.bin
          chmod +x sukisu_setup.bin
          ./sukisu_setup.bin
          rm -f ./sukisu_setup.bin
      - name: Setup Patches
        run: |
          cd kernel_workspace
          if [ "${{ github.event.inputs.SUSFS }}" == "On" ]; then
            git clone https://github.com/cctv18/susfs4oki.git -b oki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}
          fi
          git clone https://github.com/Xiaomichael/kernel_patches.git
          git clone https://github.com/ShirkNeko/SukiSU_patch.git
          cd kernel_platform
          if [ "${{ github.event.inputs.SUSFS }}" == "On" ]; then
            cp ../susfs4oki/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
            cp ../susfs4oki/kernel_patches/fs/* ./common/fs/
            cp ../susfs4oki/kernel_patches/include/linux/* ./common/include/linux/
          else
            cp ../kernel_patches/sukisu/scope_min_manual_hooks_v1.6.patch ./common/
          fi
          cp ../kernel_patches/zram_patches/001-lz4.patch ./common/
          cp ../kernel_patches/zram_patches/lz4armv8.S ./common/lib
          cp ../kernel_patches/zram_patches/002-zstd.patch ./common/
          if [ "${{ github.event.inputs.lz4kd }}" == "On" ]; then
            cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./common/include/linux
            cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./common/lib
            cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto
            cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/
          fi
          cd ./common
          if [ "${{ github.event.inputs.lz4kd }}" == "Off" ] && [ "${{ github.event.inputs.KERNEL_VERSION }}" == "6.1" ]; then
            git apply -p1 < 001-lz4.patch || true
            patch -p1 < 002-zstd.patch || true
          fi
          if [ "${{ github.event.inputs.lz4kd }}" == "Off" ] && [ "${{ github.event.inputs.KERNEL_VERSION }}" == "6.6" ]; then
            git apply -p1 < 001-lz4.patch || true
          fi
          if [ "${{ github.event.inputs.SUSFS }}" == "On" ]; then
            fake_patched=0
            if [ "${{ github.event.inputs.ANDROID_VERSION }}" = "android14" ] && [ "${{ github.event.inputs.KERNEL_VERSION }}" = "6.1" ]; then
              if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
                echo "vma_pages Line not found. Fake Patching!"
                fake_patched=1
              fi
              if ! grep -qxF '#include <linux/dma-buf.h>' ./fs/proc/base.c; then
                sed -i '/#include <linux\/cpufreq_times.h>/a #include <linux\/dma-buf.h>' ./fs/proc/base.c
              fi
            fi
            patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
            if [ "$fake_patched" = 1 ]; then
              if [ "${{ github.event.inputs.ANDROID_VERSION }}" = "android14" ] && [ "${{ github.event.inputs.KERNEL_VERSION }}" = "6.1" ]; then
                if grep -qxF $'\t\t\tgoto show_pad;' ./fs/proc/task_mmu.c; then
                  sed -i -e 's/goto show_pad;/return 0;/' ./fs/proc/task_mmu.c
                fi
              fi
            fi
          else
            patch -p1 -F 3 < scope_min_manual_hooks_v1.6.patch || true
          fi
      - name: Apply SCHED Patch
        if: ${{ github.event.inputs.KERNEL_VERSION == '6.6' }}
        run: |
          cd kernel_workspace/kernel_platform/common
          if [ "${{ github.event.inputs.FEIL }}" == "oneplus_ace5_ultra" ] || [ "${{ github.event.inputs.FEIL }}" = "oneplus_ace5_ultra_b" ]; then
              git clone https://github.com/Numbersf/SCHED_PATCH.git -b "mt6991"
          else
              git clone https://github.com/Numbersf/SCHED_PATCH.git -b "sm8750"
          fi
          cp ./SCHED_PATCH/fengchi_${{ github.event.inputs.FEIL }}.patch ./
          if [[ -f "fengchi_${{ github.event.inputs.FEIL }}.patch" ]]; then
            dos2unix "fengchi_${{ github.event.inputs.FEIL }}.patch"
            patch -p1 -F 3 < "fengchi_${{ github.event.inputs.FEIL }}.patch" || true
          else
            sed -i '1iobj-y += hmbird_patch.o' drivers/Makefile
            wget https://github.com/Numbersf/Action-Build/raw/SukiSU-Ultra/patches/hmbird_patch.patch
            patch -p1 -F 3 < hmbird_patch.patch || true
          fi
      - name: Configure Kernel Options
        run: |
          cd kernel_workspace/kernel_platform
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [ "${{ github.event.inputs.KPM }}" == "On" ]; then
            echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          if [ "${{ github.event.inputs.SUSFS }}" == "On" ]; then
            echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> ./common/arch/arm64/configs/gki_defconfig
          else
            echo "CONFIG_KSU_SUSFS=n" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [ "${{ github.event.inputs.bbg }}" == "On" ] && [ "${{ github.event.inputs.KPM }}" == "Off" ]; then
            echo 'CONFIG_BBG=y' >> ./common/arch/arm64/configs/gki_defconfig
            echo 'CONFIG_LSM="landlock,lockdown,yama,loadpin,safesetid,integrity,selinux,smack,tomoyo,apparmor,bpf,baseband_guard"' >> ./common/arch/arm64/configs/gki_defconfig
          fi
          if [ "${{ github.event.inputs.bbr }}" == "On" ]; then
            echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_NET_SCH_FQ=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_BIC=n" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_HTCP=n" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          if [ "${{ github.event.inputs.lz4kd }}" == "On" ]; then
            echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_LZ4K_OPLUS=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_ZRAM_WRITEBACK=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          if [ "${{ github.event.inputs.KERNEL_VERSION }}" == "6.1" ] || [ "${{ github.event.inputs.KERNEL_VERSION }}" == "6.6" ]; then
            echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          if [ "${{ github.event.inputs.proxy }}" == "On" ]; then
            echo "CONFIG_BPF_STREAM_PARSER=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_NETFILTER_XT_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_MAX=65534" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_BITMAP_IP=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_BITMAP_IPMAC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_BITMAP_PORT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IP=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPMARK=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPPORT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPPORTIP=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPPORTNET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPMAC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_MAC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NETPORTNET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NETNET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NETPORT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NETIFACE=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_LIST_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP6_NF_NAT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP6_NF_TARGET_MASQUERADE=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          if [ "${{ github.event.inputs.KERNEL_VERSION }}" == "5.10" ] || [ "${{ github.event.inputs.KERNEL_VERSION }}" == "5.15" ]; then
            sed -i 's/^CONFIG_LTO=n/CONFIG_LTO=y/' ./common/arch/arm64/configs/gki_defconfig
            sed -i 's/^CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' ./common/arch/arm64/configs/gki_defconfig
            sed -i 's/^CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' ./common/arch/arm64/configs/gki_defconfig
          fi
          echo "CONFIG_HEADERS_INSTALL=n" >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
      - name: Build Kernel
        run: |
          echo "Starting kernel build..."
          export KBUILD_BUILD_USER="xiaoxiaow"
          export KBUILD_BUILD_HOST="xiaoxiaow_build"
          if [ "${{ github.event.inputs.KERNEL_VERSION }}" == "6.1" ]; then
            export KBUILD_BUILD_TIMESTAMP="Tue Mar 10 03:53:33 UTC 2026"
            export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r487747c/bin:/usr/lib/ccache:$PATH"
            cd kernel_workspace/kernel_platform/common
            make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out KCFLAGS+=-O2 gki_defconfig all
          elif [ "${{ github.event.inputs.KERNEL_VERSION }}" == "6.6" ]; then
            export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:/usr/lib/ccache:$PATH"
            cd kernel_workspace/kernel_platform/common
            make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out KCFLAGS+=-O2 gki_defconfig all
          elif [ "${{ github.event.inputs.KERNEL_VERSION }}" == "5.15" ]; then
            export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r450784e/bin:/usr/lib/ccache:$PATH"
            cd kernel_workspace/kernel_platform/common
            make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out gki_defconfig all
          elif [ "${{ github.event.inputs.KERNEL_VERSION }}" == "5.10" ]; then
            export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:/usr/lib/ccache:$PATH"
            cd kernel_workspace/kernel_platform/common
            make -j$(nproc --all) LLVM_IAS=1 LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out gki_defconfig all
          fi
          ccache -s
      - name: Package Kernel
        run: |
          git clone https://github.com/Xiaomichael/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          image_path=$(find "./kernel_workspace/kernel_platform/common/out/" -name "Image" | head -n 1)
          if [ -z "$image_path" ]; then
            echo "ERROR: No Image found!"
            exit 1
          fi
          echo "Found Image at: $image_path"
          cp "$image_path" ./AnyKernel3/Image
      - name: Set Artifact Name
        id: set_name
        run: |
          if [ "${{ github.event.inputs.lz4kd }}" = "On" ]; then
            BASE_NAME="${{ github.event.inputs.FEIL }}_SukiSU_Ultra_lz4kd_v1"
          elif [ "${{ github.event.inputs.KERNEL_VERSION }}" = "6.1" ]; then
            BASE_NAME="${{ github.event.inputs.FEIL }}_SukiSU_Ultra_lz4_zstd_v1"
          elif [ "${{ github.event.inputs.KERNEL_VERSION }}" = "6.6" ]; then
            BASE_NAME="${{ github.event.inputs.FEIL }}_SukiSU_Ultra_lz4_v1"
          else
            BASE_NAME="${{ github.event.inputs.FEIL }}_SukiSU_Ultra_v1"
          fi
          if [ "${{ github.event.inputs.SUSFS }}" = "On" ]; then
            FINAL_NAME="${BASE_NAME}_SUSFS"
          else
            FINAL_NAME="${BASE_NAME}"
          fi
          echo "ARTIFACT_NAME=${FINAL_NAME}" >> $GITHUB_OUTPUT
      - name: Upload Kernel
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.set_name.outputs.ARTIFACT_NAME }}
          path: ./AnyKernel3/*
          retention-days: 5