name: SukiSU Build Master
on:
  workflow_dispatch:
    inputs:
      FEIL:
        description: "Device"
        required: true
        type: string
        default: "oneplus_ace5"
      CPU:
        description: "CPU"
        required: true
        type: string
        default: "sm8650"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main build
        run: |
          echo "Building ${{ github.event.inputs.FEIL }} with ${{ github.event.inputs.CPU }}"
          echo "::notice::SukiSU Ultra Build Started"
